version: '3'

services:
  users-service:
    container_name: user_service_api
    build: 
      context: ./users-service/
    ports:
      - 7101:7101
    depends_on: 
      - users-service-db
    networks:
      - conect_service

  users-service-db:
    container_name: user_service_db
    ports:
      - 7201:3306
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    networks:
      - conect_service

  chat-service:
    container_name: chat_service
    build:
      context: ./chat-service/
    ports:
      - 7100:7100
    depends_on:
      - chat-service-db
    links:
      - chat-service-db

  chat-service-db:
    image: mysql:5.7.20
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 7200:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports: 
      - 7300:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on: 
      - users-service-db
      - chat-service-db
    links: 
      - users-service-db
      - chat-service-db

  api-gateway:
    container_name: api_gateway
    build: 
      context: ./api-gateway/
    ports:
      - 7000:7000 
    depends_on:
      - users-service
      - chat-service



networks: 
  conect_service:

