version: '3'

services:
  users-service:
    container_name: user_service_api
    build: 
      context: ./users-service/
    ports:
      - 7101:7101
    depends_on: 
      - users-service-db
    networks:
      - conect_service

  users-service-db:
    container_name: user_service_db
    ports:
      - 7201:3306
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    networks:
      - conect_service

  

networks: 
  conect_service:

